# =============================================================================
# ADAPTIVE AI APPLICATION CONFIGURATION
# =============================================================================

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================
app:
    name: "adaptive-ai"
    version: "0.1.0"
    description: "Intelligent LLM Infrastructure with Smart Model Selection"
    environment: "development" # development, staging, production
    debug: false

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
server:
    host: "0.0.0.0"
    port: 8000
    workers: 1
    timeout: 30
    max_requests: 1000
    max_requests_jitter: 50

# =============================================================================
# LITSERVE CONFIGURATION
# =============================================================================
litserve:
    accelerator: "auto" # auto, cpu, gpu, cuda, mps
    devices: "auto" # auto, 1, 2, etc.
    max_batch_size: 8
    batch_timeout: 0.05
    workers: 1
    timeout: 30.0

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging:
    level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
    format: "json" # json, text
    file: null # null for stdout, or path to log file
    max_file_size: "10MB"
    backup_count: 5

# =============================================================================
# METRICS AND MONITORING
# =============================================================================
metrics:
    enabled: true
    endpoint: "/metrics"
    include_model_metrics: true
    include_performance_metrics: true
    prometheus:
        enabled: true
        port: 9090

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================
security:
    api_key_required: false
    rate_limiting:
        enabled: true
        requests_per_minute: 60
        burst_size: 10
    cors:
        enabled: true
        origins: ["*"]
        methods: ["GET", "POST", "OPTIONS"]
        headers: ["*"]

# =============================================================================
# HEALTH CHECK CONFIGURATION
# =============================================================================
health:
    endpoint: "/health"
    check_models: true
    check_dependencies: true
    timeout: 5.0
