import { z } from "zod";

export const messageRoleSchema = z.enum(["system", "user", "assistant"]);

// --- Message Schemas ---
export const createMessageSchema = z.object({
	conversationId: z.number(),
	role: messageRoleSchema,
	content: z.string().min(1),
	id: z.string().optional(), // Usually generated by DB, but included if client can suggest
	createdAt: z.union([z.date(), z.string().datetime()]).optional(),
	reasoning: z.string().nullable().optional(),
	annotations: z.string().nullable().optional(),
	parts: z.string().nullable().optional(),
	experimentalAttachments: z.string().nullable().optional(),
});

export const updateMessageSchema = z.object({
	id: z.string(), // Message ID to update
	content: z.string().min(1).optional(),
	reasoning: z.string().nullable().optional(),
	annotations: z.string().nullable().optional(),
	parts: z.string().nullable().optional(),
	experimentalAttachments: z.string().nullable().optional(),
});

// --- Conversation Schemas ---
export const createConversationSchema = z.object({
	title: z.string().min(1),
	pinned: z.boolean().optional(),
});

export const updateConversationSchema = z.object({
	id: z.number(), // Conversation ID to update
	title: z.string().min(1).optional(),
	pinned: z.boolean().optional(),
});

export const getConversationsOptionsSchema = z.object({
	pinned: z.boolean().optional(),
	includeMessages: z.boolean().optional(),
});
