[tool.mypy]
python_version = "3.11"
exclude = [
    "benchmarks/",
    "analysis/",
    "adaptive-app/",
    "adaptive-backend/",
    "adaptive-docs/"
]
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = false
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
    "adaptive_ai.*"
]
disallow_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict_equality = true