# NVIDIA Prompt Task Complexity Classifier Configuration

deployment:
  app_name: "${MODAL_APP_NAME:prompt-task-complexity-classifier}"
  model_name: "${MODEL_NAME:nvidia/prompt-task-and-complexity-classifier}"
  gpu_type: "${GPU_TYPE:T4}"
  timeout: ${TIMEOUT:600} # Container timeout in seconds
  scaledown_window: ${SCALEDOWN_WINDOW:300} # Scaledown window in seconds
  max_containers: ${MAX_CONTAINERS:1}
  min_containers: ${MIN_CONTAINERS:0}
  modal_secret_name: "${MODAL_SECRET_NAME:jwt}"
