# NVIDIA Prompt Task Complexity Classifier Configuration

service:
  name: "${SERVICE_NAME:nvidia-prompt-classifier}"
  modal_url: "${MODAL_URL:test}"
  timeout: ${HTTP_TIMEOUT:120} # HTTP client timeout in seconds

test:
  test_user: "${TEST_USER:claude_test}"
  test_subject: "${TEST_SUBJECT:test_user}"

deployment:
  app_name: "${MODAL_APP_NAME:prompt-task-complexity-classifier}"
  model_name: "${MODEL_NAME:nvidia/prompt-task-and-complexity-classifier}"
  gpu_type: "${GPU_TYPE:T4}"
  ml_timeout: ${ML_TIMEOUT:600} # ML container timeout in seconds
  web_timeout: ${WEB_TIMEOUT:300} # Web container timeout in seconds
  scaledown_window: ${SCALEDOWN_WINDOW:300} # Scaledown window in seconds
  max_containers: ${MAX_CONTAINERS:1}
  min_containers: ${MIN_CONTAINERS:0}
  modal_secret_name: "${MODAL_SECRET_NAME:jwt}"
