# Adaptive AI Configuration
# Environment variables: ${VAR_NAME:default_value}

# Server settings
server:
  host: "${HOST:::}"
  port: ${PORT:8000}

# FastAPI settings
fastapi:
  workers: ${FASTAPI_WORKERS:1}
  access_log: ${FASTAPI_ACCESS_LOG:true}
  log_level: ${FASTAPI_LOG_LEVEL:info}

# Logging settings
logging:
  level: ${LOG_LEVEL:INFO}

