global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go-backend"
    static_configs:
      - targets: ["backend-go:8080"]

  - job_name: "adaptive-ai"
    static_configs:
      - targets: ["backend-python:8000"]

