[project]
name = "adaptive-ai"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.12,<0.116.0",
  "uvicorn>=0.34.2,<0.35.0",
  "numpy>=2.2.6,<3.0.0",
  "scikit-learn>=1.6.1,<2.0.0",
  "huggingface-hub>=0.32.0,<0.33.0",
  "transformers>=4.52.3,<5.0.0",
  "torch>=2.7.0,<2.8.0",
  "mypy>=1.15.0,<2.0.0",
  "black>=25.1.0,<26.0.0",
  "ruff>=0.11.11,<0.12.0",
  "microsoft-python-type-stubs @ git+https://github.com/microsoft/python-type-stubs.git",
  "pytest>=8.3.5,<9.0.0",
  "prometheus-client>=0.22.0,<0.23.0",
  "prometheus-fastapi-instrumentator>=7.1.0,<8.0.0",
  "litserve>=0.2.10,<0.3.0",
  "pydantic>=2.11.5,<3.0.0",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^6.0.0"
black = "^25.1.0"
