[project]
name = "adaptive-ai"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "numpy==1.26.4",
  "scikit-learn==1.6.1",
  "huggingface-hub==0.32.2",
  "transformers==4.50.3",
  "torch==2.2.2",
  "mypy==1.15.0",
  "ruff==0.4.4",
  "safetensors==0.5.3",
  "pytest==8.3.5",
  "litserve==0.2.10",
  "pydantic==2.11.1",
]

[build-system]
requires = ["poetry-core>=1.7.0,<2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest-cov = "6.1.1"
black = "^25.1.0"
