[project]
name = "adaptive-backend"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi (>=0.115.8,<0.116.0)",
  "uvicorn (>=0.34.0,<0.35.0)",
  "numpy (>=2.2.3,<3.0.0)",
  "huggingface-hub (>=0.29.1,<0.30.0)",
  "transformers (>=4.49.0,<5.0.0)",
  "torch (>=2.6.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
