[project]
name = "adaptive-ai"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "numpy>=1.24.0,<2.0.0",
  "scikit-learn>=1.6.1,<2.0.0",
  "huggingface-hub>=0.32.0,<0.33.0",
  "transformers>=4.52.3,<5.0.0",
  "torch==2.2",
  "mypy>=1.15.0,<2.0.0",
  "black>=25.1.0,<26.0.0",
  "ruff>=0.11.11,<0.12.0",
  "microsoft-python-type-stubs @ git+https://github.com/microsoft/python-type-stubs.git",
  "pytest>=8.3.5,<9.0.0",
  "pytest-cov>=6.0.0,<7.0.0",
  "litserve>=0.2.10,<0.3.0",
  "pydantic>=2.11.5,<3.0.0",
  "types-requests>=2.31.0.20240125",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "core" },
    { include = "models" },
    { include = "services" }
]

[tool.poetry.group.dev.dependencies]
pytest-cov = "^6.0.0"
black = "^25.1.0"

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = ["transformers.*", "torch.*", "huggingface_hub.*", "litserve.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "numpy.*"
follow_imports = "skip"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "--cov=. --cov-report=xml"