/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/_home'
import { Route as ApiplatformImport } from './routes/_api_platform'
import { Route as IndexImport } from './routes/index'
import { Route as HomeHomeImport } from './routes/_home/home'
import { Route as ApiplatformApiplatformImport } from './routes/_api_platform/api_platform'
import { Route as HomeConversationsConversationIdImport } from './routes/_home/conversations/$conversationId'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const ApiplatformRoute = ApiplatformImport.update({
  id: '/_api_platform',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeHomeRoute = HomeHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HomeRoute,
} as any)

const ApiplatformApiplatformRoute = ApiplatformApiplatformImport.update({
  id: '/api_platform',
  path: '/api_platform',
  getParentRoute: () => ApiplatformRoute,
} as any)

const HomeConversationsConversationIdRoute =
  HomeConversationsConversationIdImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => HomeRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_api_platform': {
      id: '/_api_platform'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ApiplatformImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_api_platform/api_platform': {
      id: '/_api_platform/api_platform'
      path: '/api_platform'
      fullPath: '/api_platform'
      preLoaderRoute: typeof ApiplatformApiplatformImport
      parentRoute: typeof ApiplatformImport
    }
    '/_home/home': {
      id: '/_home/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeHomeImport
      parentRoute: typeof HomeImport
    }
    '/_home/conversations/$conversationId': {
      id: '/_home/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof HomeConversationsConversationIdImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

interface ApiplatformRouteChildren {
  ApiplatformApiplatformRoute: typeof ApiplatformApiplatformRoute
}

const ApiplatformRouteChildren: ApiplatformRouteChildren = {
  ApiplatformApiplatformRoute: ApiplatformApiplatformRoute,
}

const ApiplatformRouteWithChildren = ApiplatformRoute._addFileChildren(
  ApiplatformRouteChildren,
)

interface HomeRouteChildren {
  HomeHomeRoute: typeof HomeHomeRoute
  HomeConversationsConversationIdRoute: typeof HomeConversationsConversationIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeHomeRoute: HomeHomeRoute,
  HomeConversationsConversationIdRoute: HomeConversationsConversationIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof HomeRouteWithChildren
  '/api_platform': typeof ApiplatformApiplatformRoute
  '/home': typeof HomeHomeRoute
  '/conversations/$conversationId': typeof HomeConversationsConversationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof HomeRouteWithChildren
  '/api_platform': typeof ApiplatformApiplatformRoute
  '/home': typeof HomeHomeRoute
  '/conversations/$conversationId': typeof HomeConversationsConversationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_api_platform': typeof ApiplatformRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_api_platform/api_platform': typeof ApiplatformApiplatformRoute
  '/_home/home': typeof HomeHomeRoute
  '/_home/conversations/$conversationId': typeof HomeConversationsConversationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/api_platform'
    | '/home'
    | '/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/api_platform' | '/home' | '/conversations/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/_api_platform'
    | '/_home'
    | '/_api_platform/api_platform'
    | '/_home/home'
    | '/_home/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiplatformRoute: typeof ApiplatformRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiplatformRoute: ApiplatformRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_api_platform",
        "/_home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_api_platform": {
      "filePath": "_api_platform.tsx",
      "children": [
        "/_api_platform/api_platform"
      ]
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/home",
        "/_home/conversations/$conversationId"
      ]
    },
    "/_api_platform/api_platform": {
      "filePath": "_api_platform/api_platform.tsx",
      "parent": "/_api_platform"
    },
    "/_home/home": {
      "filePath": "_home/home.tsx",
      "parent": "/_home"
    },
    "/_home/conversations/$conversationId": {
      "filePath": "_home/conversations/$conversationId.tsx",
      "parent": "/_home"
    }
  }
}
ROUTE_MANIFEST_END */
