"""
Domain-based model mappings for minion protocol.
Maps domain types to task-specific model choices for minion service.
Includes both core specialized domains and fallback mappings for additional domains.
"""

from adaptive_ai.models.llm_classification_models import DomainType
from adaptive_ai.models.llm_enums import TaskType

# Domain-based model mappings for minion protocol
# Based on supported models with their domain specializations:
# - meta-llama/Meta-Llama-3-8B-Instruct: SENSITIVE_SUBJECTS
# - google/codegemma-7b-it: COMPUTERS_AND_ELECTRONICS
# - Qwen/Qwen2.5-7B-Instruct: NEWS/BUSINESS/GENERAL + JOBS_AND_EDUCATION
# - microsoft/Phi-4-mini-reasoning: LAW_AND_GOVERNMENT + FINANCE/SCIENCE

minion_domains = {
    DomainType.BUSINESS_AND_INDUSTRIAL: {
        TaskType.OPEN_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.SUMMARIZATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.TEXT_GENERATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CHATBOT: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLASSIFICATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLOSED_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.REWRITE: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.BRAINSTORMING: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.EXTRACTION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.OTHER: "Qwen/Qwen2.5-7B-Instruct",
    },
    DomainType.HEALTH: {
        TaskType.OPEN_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.SUMMARIZATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.TEXT_GENERATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CHATBOT: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLASSIFICATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLOSED_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.REWRITE: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.BRAINSTORMING: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.EXTRACTION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.OTHER: "Qwen/Qwen2.5-7B-Instruct",
    },
    DomainType.NEWS: {
        TaskType.OPEN_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.SUMMARIZATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.TEXT_GENERATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CHATBOT: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLASSIFICATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLOSED_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.REWRITE: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.BRAINSTORMING: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.EXTRACTION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.OTHER: "Qwen/Qwen2.5-7B-Instruct",
    },
    DomainType.OTHERDOMAINS: {
        TaskType.OPEN_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.SUMMARIZATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.TEXT_GENERATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CHATBOT: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLASSIFICATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLOSED_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.REWRITE: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.BRAINSTORMING: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.EXTRACTION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.OTHER: "Qwen/Qwen2.5-7B-Instruct",
    },
    DomainType.REAL_ESTATE: {
        TaskType.OPEN_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.SUMMARIZATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.TEXT_GENERATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CHATBOT: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLASSIFICATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLOSED_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.REWRITE: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.BRAINSTORMING: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.EXTRACTION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.OTHER: "Qwen/Qwen2.5-7B-Instruct",
    },
    DomainType.COMPUTERS_AND_ELECTRONICS: {
        TaskType.CODE_GENERATION: "google/codegemma-7b-it",
        TaskType.OPEN_QA: "google/codegemma-7b-it",
        TaskType.SUMMARIZATION: "google/codegemma-7b-it",
        TaskType.TEXT_GENERATION: "google/codegemma-7b-it",
        TaskType.CHATBOT: "google/codegemma-7b-it",
        TaskType.CLASSIFICATION: "google/codegemma-7b-it",
        TaskType.CLOSED_QA: "google/codegemma-7b-it",
        TaskType.REWRITE: "google/codegemma-7b-it",
        TaskType.BRAINSTORMING: "google/codegemma-7b-it",
        TaskType.EXTRACTION: "google/codegemma-7b-it",
        TaskType.OTHER: "google/codegemma-7b-it",
    },
    DomainType.INTERNET_AND_TELECOM: {
        TaskType.CODE_GENERATION: "google/codegemma-7b-it",
        TaskType.OPEN_QA: "google/codegemma-7b-it",
        TaskType.SUMMARIZATION: "google/codegemma-7b-it",
        TaskType.TEXT_GENERATION: "google/codegemma-7b-it",
        TaskType.CHATBOT: "google/codegemma-7b-it",
        TaskType.CLASSIFICATION: "google/codegemma-7b-it",
        TaskType.CLOSED_QA: "google/codegemma-7b-it",
        TaskType.REWRITE: "google/codegemma-7b-it",
        TaskType.BRAINSTORMING: "google/codegemma-7b-it",
        TaskType.EXTRACTION: "google/codegemma-7b-it",
        TaskType.OTHER: "google/codegemma-7b-it",
    },
    DomainType.FINANCE: {
        TaskType.OPEN_QA: "microsoft/Phi-4-mini-reasoning",
        TaskType.SUMMARIZATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.TEXT_GENERATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.CHATBOT: "microsoft/Phi-4-mini-reasoning",
        TaskType.CLASSIFICATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.CLOSED_QA: "microsoft/Phi-4-mini-reasoning",
        TaskType.REWRITE: "microsoft/Phi-4-mini-reasoning",
        TaskType.BRAINSTORMING: "microsoft/Phi-4-mini-reasoning",
        TaskType.EXTRACTION: "microsoft/Phi-4-mini-reasoning",
        TaskType.OTHER: "microsoft/Phi-4-mini-reasoning",
    },
    DomainType.SCIENCE: {
        TaskType.OPEN_QA: "microsoft/Phi-4-mini-reasoning",
        TaskType.SUMMARIZATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.TEXT_GENERATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.CHATBOT: "microsoft/Phi-4-mini-reasoning",
        TaskType.CLASSIFICATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.CLOSED_QA: "microsoft/Phi-4-mini-reasoning",
        TaskType.REWRITE: "microsoft/Phi-4-mini-reasoning",
        TaskType.BRAINSTORMING: "microsoft/Phi-4-mini-reasoning",
        TaskType.EXTRACTION: "microsoft/Phi-4-mini-reasoning",
        TaskType.OTHER: "microsoft/Phi-4-mini-reasoning",
    },
    DomainType.JOBS_AND_EDUCATION: {
        TaskType.OPEN_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.SUMMARIZATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.TEXT_GENERATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CHATBOT: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLASSIFICATION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.CLOSED_QA: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.REWRITE: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.BRAINSTORMING: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.EXTRACTION: "Qwen/Qwen2.5-7B-Instruct",
        TaskType.OTHER: "Qwen/Qwen2.5-7B-Instruct",
    },
    DomainType.LAW_AND_GOVERNMENT: {
        TaskType.OPEN_QA: "microsoft/Phi-4-mini-reasoning",
        TaskType.SUMMARIZATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.TEXT_GENERATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.CHATBOT: "microsoft/Phi-4-mini-reasoning",
        TaskType.CLASSIFICATION: "microsoft/Phi-4-mini-reasoning",
        TaskType.CLOSED_QA: "microsoft/Phi-4-mini-reasoning",
        TaskType.REWRITE: "microsoft/Phi-4-mini-reasoning",
        TaskType.BRAINSTORMING: "microsoft/Phi-4-mini-reasoning",
        TaskType.EXTRACTION: "microsoft/Phi-4-mini-reasoning",
        TaskType.OTHER: "microsoft/Phi-4-mini-reasoning",
    },
    DomainType.SENSITIVE_SUBJECTS: {
        TaskType.OPEN_QA: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.SUMMARIZATION: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.TEXT_GENERATION: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.CHATBOT: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.CLASSIFICATION: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.CLOSED_QA: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.REWRITE: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.BRAINSTORMING: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.EXTRACTION: "meta-llama/Meta-Llama-3-8B-Instruct",
        TaskType.OTHER: "meta-llama/Meta-Llama-3-8B-Instruct",
    },
}

# Add missing domains that should use OTHERDOMAINS models
for domain in [
    DomainType.AUTOS_AND_VEHICLES,
    DomainType.BOOKS_AND_LITERATURE,
    DomainType.ADULT,
    DomainType.ONLINE_COMMUNITIES,
    DomainType.TRAVEL_AND_TRANSPORTATION,
    DomainType.SHOPPING,
    DomainType.ARTS_AND_ENTERTAINMENT,
    DomainType.HOME_AND_GARDEN,
    DomainType.HOBBIES_AND_LEISURE,
    DomainType.PEOPLE_AND_SOCIETY,
    DomainType.FOOD_AND_DRINK,
    DomainType.SPORTS,
    DomainType.BEAUTY_AND_FITNESS,
    DomainType.PETS_AND_ANIMALS,
    DomainType.GAMES,
    DomainType.REFERENCE,
]:
    minion_domains[domain] = minion_domains[DomainType.OTHERDOMAINS].copy()
