# API Authentication Configuration
# Set your API key here or use ADAPTIVE_API_KEY environment variable

adaptive:
  api_key: ""

default_auth:
  type: "api_key"
  header: "X-Stainless-API-Key"
  prefix: ""

