import { FC } from "react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

interface ProviderBadgeProps {
  provider?: string;
  model?: string;
  className?: string;
}

const ProviderBadge: FC<ProviderBadgeProps> = ({
  provider,
  model,
  className,
}) => {
  if (!provider && !model) return null;

  const getProviderLogo = () => {
    switch (provider?.toLowerCase()) {
      case "openai":
        return "/openai.jpeg";
      case "anthropic":
        return "/anthropic.jpeg";
      case "groq":
        return "/groq.png";
      case "deepseek":
        return "/deepseek.svg";
      default:
        return "/vite.svg";
    }
  };

  const logo = getProviderLogo();

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <div
            className={cn(
              "flex items-center gap-1.5 text-xs text-muted-foreground",
              className,
            )}
          >
            <div className="relative w-3.5 h-3.5">
              <img
                src={logo}
                alt={`${provider} logo`}
                className="object-contain"
              />
            </div>

            <span className="truncate max-w-[120px]">
              {" "}
              Generated by {model}
            </span>
          </div>
        </TooltipTrigger>
        <TooltipContent side="top" className="text-xs">
          `${provider} · ${model}`
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};

export default ProviderBadge;
