import { FC } from "react";
import { cn } from "@/lib/utils";

interface ProviderBadgeProps {
  provider: string;
  model: string;
  className?: string;
}

const ProviderBadge: FC<ProviderBadgeProps> = ({
  provider,
  model,
  className,
}) => {
  const getProviderLogo = () => {
    switch (provider?.toLowerCase()) {
      case "openai":
        return "/openai.png";
      case "anthropic":
        return "/anthropic.jpeg";
      case "groq":
        return "/groq.png";
      case "deepseek":
        return "/deepseek.svg";
      default:
        return "/vite.svg";
    }
  };

  const logo = getProviderLogo();

  return (
    <div
      className={cn(
        "flex items-center gap-1.5 text-xs text-muted-foreground",
        className,
      )}
    >
      <div className="relative w-3.5 h-3.5">
        <img src={logo} alt={`${provider} logo`} className="object-contain" />
      </div>
      <span> Generated by {model}</span>
    </div>
  );
};

export default ProviderBadge;
