name: Python SDK CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/adaptive-python/adaptive
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: libraries/adaptive-python/adaptive/.venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('libraries/adaptive-python/adaptive/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          # Check if pyproject.toml exists
          if [ -f "pyproject.toml" ]; then
            poetry install --no-interaction --no-root
          else
            echo "No pyproject.toml found in the current directory"
            ls -la
            exit 1
          fi

      - name: Install project
        run: |
          # Check if pyproject.toml exists
          if [ -f "pyproject.toml" ]; then
            poetry install --no-interaction
          else
            echo "No pyproject.toml found in the current directory"
            ls -la
            exit 1
          fi

      - name: Run black
        run: |
          poetry run black --check .

      - name: Run ruff
        run: |
          poetry run ruff check .

      - name: Install type stubs for mypy
        run: |
          poetry run pip install types-requests

      - name: Run mypy
        run: |
          poetry run mypy .

      - name: Run pytest with coverage
        run: |
          poetry run pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: libraries/adaptive-python/adaptive/coverage.xml
          fail_ci_if_error: false

      - name: Check for security vulnerabilities
        run: |
          poetry run pip install safety
          poetry export -f requirements.txt --without-hashes -o requirements.txt
          poetry run safety scan -r requirements.txt

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/adaptive-python/adaptive
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build package
        run: |
          # Check if pyproject.toml exists
          if [ -f "pyproject.toml" ]; then
            poetry build
          else
            echo "No pyproject.toml found in the current directory"
            ls -la
            exit 1
          fi

      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: libraries/adaptive-python/adaptive/dist/

      - name: Check package metadata
        run: |
          pip install twine
          twine check dist/*

  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/adaptive-python/adaptive
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Check if pyproject.toml exists
          if [ -f "pyproject.toml" ]; then
            poetry install --no-interaction
          else
            echo "No pyproject.toml found in the current directory"
            ls -la
            exit 1
          fi

      - name: Build documentation
        run: |
          if [ -d "docs" ]; then
            cd docs && poetry run make html
          else
            echo "No docs directory found"
            ls -la
          fi

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        if: success() && hashFiles('libraries/adaptive-python/adaptive/docs/_build/html/**') != ''
        with:
          name: documentation
          path: libraries/adaptive-python/adaptive/docs/_build/html/
