name: Frontend CI/CD (Production)
on:
  push:
    branches: [main]
    paths:
      - "adaptive-app/**"
      - ".github/workflows/adaptive-app-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "adaptive-app/**"
      - ".github/workflows/adaptive-app-ci.yml"
  workflow_dispatch:

env:
  NODE_VERSION: "24"
  PNPM_VERSION: "10"
  WORKING_DIR: "./adaptive-app"

jobs:
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.WORKING_DIR }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm exec prisma generate

      - name: Run Biome linter
        run: pnpm run check

      - name: Run TypeScript type check
        run: pnpm run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.WORKING_DIR }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build
        env:
          # Build-time environment variables
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          REDIS_URL: ${{ secrets.FRONTEND_REDIS_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADAPTIVE_API_BASE_URL: ${{ secrets.ADAPTIVE_API_BASE_URL }}

  migrate:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: [build]
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.WORKING_DIR }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm exec prisma generate

      - name: Run database migrations (Production)
        run: pnpm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
