name: Deploy AI Service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/ai_service_deploy.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKENDPYTHON_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKENDPYTHON_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKENDPYTHON_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/adaptive_ai
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: adaptiveregistry.azurecr.io
          registryUsername: ${{ secrets.BACKENDPYTHON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKENDPYTHON_REGISTRY_PASSWORD }}
          containerAppName: backend-python
          resourceGroup: adaptive
          imageToBuild: adaptiveregistry.azurecr.io/backend-python:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
