name: Trigger auto deployment for frontend-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/frontend-dev-AutoDeployTrigger-b121022e-362b-4fdf-8463-87cb4f81fa4b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FRONTENDDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRONTENDDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRONTENDDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/adaptive-app
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: llmadaptiveregistry.azurecr.io
          registryUsername: ${{ secrets.FRONTENDDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONTENDDEV_REGISTRY_PASSWORD }}
          containerAppName: frontend-dev
          resourceGroup: adaptive
          imageToBuild: llmadaptiveregistry.azurecr.io/frontend-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


