name: JavaScript SDK Release

on:
  push:
    branches: [main]
    paths:
      - "libraries/adaptive-js/**"
    tags:
      - "v*-js"

jobs:
  publish-js:
    name: 🚀 Publish JavaScript SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/adaptive-js

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
