name: JavaScript SDK CI

on:
  push:
    branches: [main, master]
    paths:
      - "libraries/adaptive-js/**"
      - ".github/workflows/javascript-sdk-ci.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "libraries/adaptive-js/**"
      - ".github/workflows/javascript-sdk-ci.yml"

jobs:
  javascript:
    name: 🧪 JS SDK – CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/adaptive-js

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bunx tsc --noEmit

      - name: Run tests
        run: bun test
