name: Model Router Dev CI/CD

on:
  push:
    branches: [dev]
    paths:
      - "adaptive_ai/model_router/**"
      - ".github/workflows/model-router-dev-ci.yml"
      - ".github/scripts/**"
  pull_request:
    branches: [dev]
    paths:
      - "adaptive_ai/model_router/**"
      - ".github/workflows/model-router-dev-ci.yml"
      - ".github/scripts/**"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  WORKING_DIR: "./adaptive_ai/model_router"

jobs:
  test:
    name: Test & Coverage - Model Router
    runs-on: blacksmith-4vcpu-ubuntu-2404
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev --group test

      - name: Run unit tests only
        run: make test-unit

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          file: ${{ env.WORKING_DIR }}/coverage.xml
          flags: backend-python
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint & Format - Model Router
    runs-on: blacksmith-4vcpu-ubuntu-2404
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run type checking
        run: uv run mypy .

      - name: Run linting
        run: uv run ruff check . --output-format=github

      - name: Check formatting
        run: uv run black . --check --diff --fast

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Depot CLI
        uses: depot/setup-action@v1
      - name: Build and push Docker image
        uses: depot/build-push-action@v1
        with:
          project: 0nqk9ktvv8
          context: ${{ env.WORKING_DIR }}
          file: ${{ env.WORKING_DIR }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/model-router:dev
            ghcr.io/${{ github.repository }}/model-router:dev-${{ github.sha }}

