name: Monitoring CI

on:
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/monitoring-ci.yml"
  workflow_dispatch:

jobs:
  deploy-grafanamonitoring:
    name: Build & Deploy Grafana Monitoring
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GRAFANAMONITORING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GRAFANAMONITORING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GRAFANAMONITORING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/grafana/provisioning/datasources
          dockerfilePath: Dockerfile
          registryUrl: adaptiveregistry.azurecr.io
          registryUsername: ${{ secrets.GRAFANAMONITORING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GRAFANAMONITORING_REGISTRY_PASSWORD }}
          containerAppName: grafanamonitoring
          resourceGroup: adaptive
          imageToBuild: adaptiveregistry.azurecr.io/grafanamonitoring:${{ github.sha }}

  deploy-prometheusmonitoring:
    name: Build & Deploy Prometheus Monitoring
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PROMETHEUSMONITORING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PROMETHEUSMONITORING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PROMETHEUSMONITORING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/monitoring
          dockerfilePath: Dockerfile
          registryUrl: adaptiveregistry.azurecr.io
          registryUsername: ${{ secrets.PROMETHEUSMONITORING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PROMETHEUSMONITORING_REGISTRY_PASSWORD }}
          containerAppName: prometheusmonitoring
          resourceGroup: adaptive
          imageToBuild: adaptiveregistry.azurecr.io/prometheusmonitoring:${{ github.sha }}
