name: Monitoring CI/CD

on:
    push:
        branches: [main]
        paths:
            - "grafana/**"
            - "monitoring/**"
            - ".github/workflows/monitoring-ci.yml"
    workflow_dispatch:

env:
    REGISTRY_URL: adaptiveregistry.azurecr.io
    RESOURCE_GROUP: adaptive

jobs:
    deploy-grafana:
        name: Deploy Grafana
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.GRAFANAMONITORING_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.GRAFANAMONITORING_AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.GRAFANAMONITORING_AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Grafana to Azure Container Apps
              uses: azure/container-apps-deploy-action@v2
              with:
                  appSourcePath: ${{ github.workspace }}/grafana/provisioning/datasources
                  dockerfilePath: Dockerfile
                  registryUrl: ${{ env.REGISTRY_URL }}
                  registryUsername: ${{ secrets.GRAFANAMONITORING_REGISTRY_USERNAME }}
                  registryPassword: ${{ secrets.GRAFANAMONITORING_REGISTRY_PASSWORD }}
                  containerAppName: grafanamonitoring
                  resourceGroup: ${{ env.RESOURCE_GROUP }}
                  imageToBuild: ${{ env.REGISTRY_URL }}/grafanamonitoring:${{ github.sha }}

    deploy-prometheus:
        name: Deploy Prometheus
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.PROMETHEUSMONITORING_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.PROMETHEUSMONITORING_AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.PROMETHEUSMONITORING_AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Prometheus to Azure Container Apps
              uses: azure/container-apps-deploy-action@v2
              with:
                  appSourcePath: ${{ github.workspace }}/monitoring
                  dockerfilePath: Dockerfile
                  registryUrl: ${{ env.REGISTRY_URL }}
                  registryUsername: ${{ secrets.PROMETHEUSMONITORING_REGISTRY_USERNAME }}
                  registryPassword: ${{ secrets.PROMETHEUSMONITORING_REGISTRY_PASSWORD }}
                  containerAppName: prometheusmonitoring
                  resourceGroup: ${{ env.RESOURCE_GROUP }}
                  imageToBuild: ${{ env.REGISTRY_URL }}/prometheusmonitoring:${{ github.sha }}
