name: Trigger auto deployment for prompt-classifier

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/prompt-classifier-AutoDeployTrigger-a4a446cd-a863-4aba-b19f-a3ce6f4e225f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PROMPTCLASSIFIER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PROMPTCLASSIFIER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PROMPTCLASSIFIER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/adaptive_ai
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: llmadaptiveregistry.azurecr.io
          registryUsername: ${{ secrets.PROMPTCLASSIFIER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PROMPTCLASSIFIER_REGISTRY_PASSWORD }}
          containerAppName: prompt-classifier
          resourceGroup: adaptive
          imageToBuild: llmadaptiveregistry.azurecr.io/prompt-classifier:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


