name: Task Complexity Classifier Dev CI/CD

on:
  push:
    branches: [dev]
    paths:
      - "adaptive_ai/prompt_task_complexity_classifier/**"

  pull_request:
    branches: [dev]
    paths:
      - "adaptive_ai/prompt_task_complexity_classifier/**"

  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  WORKING_DIR: "./adaptive_ai/prompt_task_complexity_classifier"

jobs:
  test:
    name: Test & Lint - Task Complexity Classifier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run type checking
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest tests/unit

      - name: Run linting
        run: uv run ruff check . --output-format=github

      - name: Check formatting
        run: uv run black . --check --diff

  deploy-dev:
    name: Deploy Task Complexity Classifier - Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    environment: development
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deployment dependencies
        run: |
          pip install modal

      - name: Deploy to Dev
        run: |
          echo "🚀 Deploying Prompt Task Complexity Classifier to dev environment..."
          modal deploy deploy.py
          echo "✅ Deployment to dev completed"
