name: Python SDK Release

on:
  push:
    branches: [main]
    paths:
      - "libraries/adaptive-python/**"
    tags:
      - "v*-py"

jobs:
  publish-python:
    name: 🚀 Publish Python SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/adaptive-python/adaptive
    permissions:
      id-token: write # Required for trusted PyPI publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Build Package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
