name: Sync dev with main after merge

on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      - name: Force-push main to dev
        run: |
          git push origin main:dev --force
